apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: bootiful-client
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: bootiful-client
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: spring-boot_spring-cloud-gateway-server
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: "cloud"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/tap-labs/demo-bootiful-spring-boot-3
      ref:
        branch: main
    subPath: client
